name: my-fastapi-app

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8080:8080
    volumes:
      - .:/app