name: Deploy to Oketo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: my-username/my-fastapi-image:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Oketo
        uses: okteto/action@v2
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          manifest: okteto.yml
      - name: Create and deploy database
        uses: okteto/db@v1
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          name: my-database
          image: mysql:5.7
          env: |
            MYSQL_ROOT_PASSWORD=my-root-password
            MYSQL_DATABASE=my-database-name
          port: 3306
          replicas: 1
      - name: Update environment variables
        run: |
          echo "DATABASE_URL=mysql://root:my-root-password@my-database:3306/my-database-name" >> $GITHUB_ENV